import { Composition } from "remotion";
import { BrilliantReel, totalFrames } from "./compositions/BrilliantReel";
import { BrandCard, BrandCardTransparent, ReeganCreditCard, ReeganCreditCardTransparent } from "./compositions/CardLoops";
import { DEMO_STORYBOARD } from "./storyboard/demo";
import { GIRI_FIROUZJA_STORYBOARD } from "./storyboard/giri-firouzja";
import { PRAGG_SINDAROV_STORYBOARD } from "./storyboard/pragg-sindarov";
import { WIN_IN_4_MOVES_STORYBOARD } from "./storyboard/win-in-4-moves";
import { WIN_IN_4_MEME_STORYBOARD } from "./storyboard/win-in-4-meme";
// AI-style storyboard, generated by the script at scripts/generate-reel-script.mjs
// (or hand-written in Opus-4.7 style when the script can't authenticate).
import praggAiStoryboard from "./storyboard/generated/pragg-ai.json";
import type { Storyboard } from "./storyboard/types";
const PRAGG_AI_STORYBOARD = praggAiStoryboard as Storyboard;

const FPS = 30;
const WIDTH = 1080;
const HEIGHT = 1920;

export const RemotionRoot: React.FC = () => {
  return (
    <>
      <Composition
        id="BrilliantReel"
        component={BrilliantReel}
        durationInFrames={totalFrames(DEMO_STORYBOARD, FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={{ storyboard: DEMO_STORYBOARD, audioSrc: "audio/reel.mp3", audioVolume: 1 }}
      />
      <Composition
        id="GiriFirouzja"
        component={BrilliantReel}
        durationInFrames={totalFrames(GIRI_FIROUZJA_STORYBOARD, FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={{ storyboard: GIRI_FIROUZJA_STORYBOARD, audioSrc: "audio/reel.mp3", audioVolume: 1 }}
      />
      <Composition
        id="PraggSindarov"
        component={BrilliantReel}
        durationInFrames={totalFrames(PRAGG_SINDAROV_STORYBOARD, FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={{
          storyboard: PRAGG_SINDAROV_STORYBOARD,
          audioSrc: "audio/hukum.mp3",
          audioVolume: 1,
          audioStartFromSec: 16.7,
        }}
      />
      <Composition
        id="WinIn4Moves"
        component={BrilliantReel}
        durationInFrames={totalFrames(WIN_IN_4_MOVES_STORYBOARD, FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={{
          storyboard: WIN_IN_4_MOVES_STORYBOARD,
          audioSrc: "audio/hukum.mp3",
          audioVolume: 1,
          audioStartFromSec: 16.7,
        }}
      />
      <Composition
        id="WinIn4Meme"
        component={BrilliantReel}
        durationInFrames={totalFrames(WIN_IN_4_MEME_STORYBOARD, FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={{
          storyboard: WIN_IN_4_MEME_STORYBOARD,
          // Synthesized ambient bed — no copyrighted music. The per-event SFX
          // (move click, capture thud, check alarm, mate boom, brilliant ding,
          // etc.) are layered on top inside MoveSequenceShot.
          audioSrc: "sfx/ambient-bed.wav",
          audioVolume: 0.55,
          audioStartFromSec: 0,
        }}
      />
      {/* AI-style storyboard loaded from JSON — drop new files into
          src/storyboard/generated/ to register more compositions. */}
      <Composition
        id="PraggAi"
        component={BrilliantReel}
        durationInFrames={totalFrames(PRAGG_AI_STORYBOARD, FPS)}
        fps={FPS}
        width={WIDTH}
        height={HEIGHT}
        defaultProps={{
          storyboard: PRAGG_AI_STORYBOARD,
          audioSrc: "sfx/ambient-bed.wav",
          audioVolume: 0.55,
          audioStartFromSec: 0,
        }}
      />
      {/* Standalone "sticker" cards — rendered as short MP4s and converted to GIFs.
          Tighter canvas dimensions than the reel so there's breathing room around
          content but no big dead bands. */}
      <Composition
        id="BrandCard"
        component={BrandCard}
        durationInFrames={FPS * 3}
        fps={FPS}
        width={1080}
        height={1400}
      />
      <Composition
        id="CreditCard"
        component={ReeganCreditCard}
        durationInFrames={FPS * 3}
        fps={FPS}
        width={1080}
        height={720}
      />
      {/* Transparent-background variants for use as GIF stickers */}
      <Composition
        id="BrandCardTransparent"
        component={BrandCardTransparent}
        durationInFrames={FPS * 3}
        fps={FPS}
        width={1080}
        height={1400}
      />
      <Composition
        id="CreditCardTransparent"
        component={ReeganCreditCardTransparent}
        durationInFrames={FPS * 3}
        fps={FPS}
        width={1080}
        height={720}
      />
    </>
  );
};
